# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    splitPerAbi: true
    buildNumber: '0.0.0.1'
    buildName: '0.0.0.1'

